# Generated by Django 5.2.9 on 2025-12-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter a short title for the note", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Write the full content of your note"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the note was created",
                    ),
                ),
            ],
        ),
    ]
